# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Configuration for the frontend dependencies
  - package-ecosystem: "npm"
    directory: "/journal-web"
    schedule:
      interval: "weekly"
    # Optional configurations for frontend
    labels:
      - "frontend"
      - "dependencies"
    assignees:
      - "hannah-sofie"

  # Configuration for the backend dependencies
  - package-ecosystem: "npm"
    directory: "/journal-backend"
    schedule:
      interval: "weekly"
    # Optional configurations for backend
    labels:
      - "backend"
      - "dependencies"
    assignees:
      - "hannah-sofie"
