services:
  journal-web:
    build: .
    ports:
      - "3001:3000"
  mongo:
    image: mongo
    restart: always
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping').ok"
      interval: 6s
      timeout: 5s
      retries: 3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
networks:
  default:
    name: journal
