version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: journal-container
    expose:
      - "${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_admin_pwd
    deploy:
      labels:
        example.label: "This is a pointless label"
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 10
        window: 120s
      resources:
        limits:
          cpus: "0.75"
          memory: 175M
        reservations:
          cpus: "0.25"
          memory: 75M
    secrets:
      - mongo_admin_pwd
    healthcheck:
      test: ["CMD-SHELL", 'mongosh --eval "db.adminCommand(''ping'').ok"']
      interval: 10s
      timeout: 5s
      retries: 3
    env_file: .mongo.env
    networks:
      journal-network:
        aliases:
          - "${MONGO_HOSTNAME}"
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"

  journal-backend:
    image: journal-image-backend
    labels:
      cool.example: "some meta information about our container"
    depends_on:
      mongo:
        condition: service_healthy
    build:
      context: ./journal-backend
      dockerfile: Dockerfile
    environment:
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_admin_pwd
    secrets:
      - mongo_admin_pwd
    env_file:
      - .mongo.env
      - .env
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - journal-network

  journal-frontend:
    image: journal-image-frontend
    labels:
      cool.example: "some meta information about our container"
    depends_on:
      - journal-backend
    build:
      context: ./journal-frontend
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - .env
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - journal-network

secrets:
  mongo_admin_pwd:
    file: ./secrets.folder/mongo_admin_pwd.txt

networks:
  journal-network:
    name: team3-network
    external: true
